# Configuración de Base de Datos
spring.datasource.url=jdbc:mysql://193.203.175.197:3306/u862422702_SOA?useSSL=false&serverTimezone=America/Guayaquil&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
spring.datasource.username=u862422702_GRUPO3
spring.datasource.password=Ambato2026@
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate MySQL
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# Optimización HikariCP (Para base de datos remota)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1200000
spring.datasource.hikari.pool-name=SistemaVentasHikariCP

# Inicialización SQL
spring.sql.init.mode=never
spring.sql.init.continue-on-error=true
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.data-locations=classpath:data.sql

# Seguridad JWT
app.jwt.secret=esta-es-una-clave-secreta-muy-larga-y-segura-para-el-sistema-de-ventas-2026-que-cumple-los-64-bytes-minimos
app.jwt.expiration=86400000

# Parámetros de Negocio
app.iva.porcentaje=15
app.empresa.nombre=Mi Empresa S.A.
app.empresa.ruc=1234567890001
app.empresa.direccion=Av. Principal 123

# Configuración de Servidor y CORS
server.port=8080
spring.web.cors.allowed-origins=http://localhost:4200
